// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeRouteApi.Data;

#nullable disable

namespace SafeRouteApi.Migrations
{
    [DbContext(typeof(SafeRouteDbContext))]
    [Migration("20251109103952_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafeRouteApi.Models.CameraRecordings", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordingId"));

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("Evidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float>("FileSize")
                        .HasColumnType("real");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int?>("ThreatId")
                        .HasColumnType("int");

                    b.HasKey("RecordingId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.HasIndex("ThreatId");

                    b.ToTable("CameraRecordings");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Companies", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyRegistration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Dispatchers", b =>
                {
                    b.Property<int>("DispatcherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispatcherId"));

                    b.Property<bool>("IsOnDuty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ShiftEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftPattern")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DispatcherId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Dispatchers");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Drivers", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<int?>("DispatcherId")
                        .HasColumnType("int");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PackageAmount")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleRegistration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DriverId");

                    b.HasIndex("DispatcherId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("SafeRouteApi.Models.EmergencyContacts", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ContactId");

                    b.HasIndex("DriverId");

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("SafeRouteApi.Models.IncidentResponses", b =>
                {
                    b.Property<int>("IncidentResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentResponseId"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("WasSuccessful")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IncidentResponseId");

                    b.HasIndex("DriverId");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentResponses");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Incidents", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<int?>("AlertId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IncidentTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("IncidentId");

                    b.HasIndex("AlertId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("SafeRouteApi.Models.MonthlyReports", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<float>("AverageResponseTime")
                        .HasColumnType("real");

                    b.Property<int>("AverageSafetyScore")
                        .HasColumnType("int");

                    b.Property<int?>("Companies")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompletedRoutes")
                        .HasColumnType("int");

                    b.Property<int>("PanicAlerts")
                        .HasColumnType("int");

                    b.Property<string>("ReportData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResolvedIncidents")
                        .HasColumnType("int");

                    b.Property<int>("SuccessfulDeliveries")
                        .HasColumnType("int");

                    b.Property<int>("ThreatDetections")
                        .HasColumnType("int");

                    b.Property<int>("TotalDeliveries")
                        .HasColumnType("int");

                    b.Property<float>("TotalDistance")
                        .HasColumnType("real");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("int");

                    b.Property<int>("TotalRoutes")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("CompanyId");

                    b.ToTable("MonthlyReports");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Notifications", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NotificationId");

                    b.HasIndex("DriverId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SafeRouteApi.Models.PanicAlerts", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<DateTime>("Alert")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AlertId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.ToTable("PanicAlerts");
                });

            modelBuilder.Entity("SafeRouteApi.Models.RiskZones", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<bool>("Incident")
                        .HasColumnType("bit");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastIncident")
                        .HasColumnType("datetime2");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ZoneId");

                    b.ToTable("RiskZones");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Routes", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<float>("ActualDistance")
                        .HasColumnType("real");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("End")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("EstimatedDistance")
                        .HasColumnType("real");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RouteStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RouteId");

                    b.HasIndex("DriverId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SafeRouteApi.Models.SafetyScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<DateTime>("CalculatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletedRoutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("IncidentScore")
                        .HasColumnType("int");

                    b.Property<int>("OverallScore")
                        .HasColumnType("int");

                    b.Property<double>("RouteCompletionScore")
                        .HasColumnType("float");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("int");

                    b.Property<int>("TotalRoutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ScoreId");

                    b.HasIndex("DriverId");

                    b.ToTable("SafetyScores");
                });

            modelBuilder.Entity("SafeRouteApi.Models.ThreatDetections", b =>
                {
                    b.Property<int>("ThreatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreatId"));

                    b.Property<byte[]>("CameraData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<bool>("ConfirmedThreat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("ManualReview")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("ThreatType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThreatId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.ToTable("ThreatDetections");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SafeRouteApi.Models.CameraRecordings", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Drivers", "Driver")
                        .WithMany("CameraRecordings")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeRouteApi.Models.Routes", "Route")
                        .WithMany("CameraRecordings")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeRouteApi.Models.ThreatDetections", "ThreatDetected")
                        .WithMany("CameraRecordings")
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("ThreatDetected");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Dispatchers", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Users", "User")
                        .WithOne("Dispatcher")
                        .HasForeignKey("SafeRouteApi.Models.Dispatchers", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Drivers", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Dispatchers", "Dispatcher")
                        .WithMany("Drivers")
                        .HasForeignKey("DispatcherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SafeRouteApi.Models.Users", "User")
                        .WithOne("Driver")
                        .HasForeignKey("SafeRouteApi.Models.Drivers", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dispatcher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRouteApi.Models.EmergencyContacts", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Drivers", "Driver")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SafeRouteApi.Models.IncidentResponses", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Drivers", "Driver")
                        .WithMany("IncidentResponses")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeRouteApi.Models.Incidents", "Incident")
                        .WithMany("IncidentResponses")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Incidents", b =>
                {
                    b.HasOne("SafeRouteApi.Models.PanicAlerts", "PanicAlert")
                        .WithMany("Incidents")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SafeRouteApi.Models.Drivers", "Driver")
                        .WithMany("Incidents")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeRouteApi.Models.Routes", "Route")
                        .WithMany("Incidents")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeRouteApi.Models.RiskZones", "RiskZone")
                        .WithMany("Incidents")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("PanicAlert");

                    b.Navigation("RiskZone");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SafeRouteApi.Models.MonthlyReports", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Companies", "Company")
                        .WithMany("MonthlyReports")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Notifications", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Drivers", "Driver")
                        .WithMany("Notifications")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SafeRouteApi.Models.PanicAlerts", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Drivers", "Driver")
                        .WithMany("PanicAlerts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeRouteApi.Models.Routes", "Route")
                        .WithMany("PanicAlerts")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Routes", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Drivers", "Driver")
                        .WithMany("Routes")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SafeRouteApi.Models.SafetyScore", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Drivers", "Driver")
                        .WithMany("SafetyScores")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SafeRouteApi.Models.ThreatDetections", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Drivers", "Driver")
                        .WithMany("ThreatDetections")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeRouteApi.Models.Routes", "Route")
                        .WithMany("ThreatDetections")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Users", b =>
                {
                    b.HasOne("SafeRouteApi.Models.Companies", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Companies", b =>
                {
                    b.Navigation("MonthlyReports");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Dispatchers", b =>
                {
                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Drivers", b =>
                {
                    b.Navigation("CameraRecordings");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("IncidentResponses");

                    b.Navigation("Incidents");

                    b.Navigation("Notifications");

                    b.Navigation("PanicAlerts");

                    b.Navigation("Routes");

                    b.Navigation("SafetyScores");

                    b.Navigation("ThreatDetections");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Incidents", b =>
                {
                    b.Navigation("IncidentResponses");
                });

            modelBuilder.Entity("SafeRouteApi.Models.PanicAlerts", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("SafeRouteApi.Models.RiskZones", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Routes", b =>
                {
                    b.Navigation("CameraRecordings");

                    b.Navigation("Incidents");

                    b.Navigation("PanicAlerts");

                    b.Navigation("ThreatDetections");
                });

            modelBuilder.Entity("SafeRouteApi.Models.ThreatDetections", b =>
                {
                    b.Navigation("CameraRecordings");
                });

            modelBuilder.Entity("SafeRouteApi.Models.Users", b =>
                {
                    b.Navigation("Dispatcher");

                    b.Navigation("Driver");
                });
#pragma warning restore 612, 618
        }
    }
}
